8 write test cases
h0peRL/Bookkeeper_Docs pull request #23
Opened 2024-02-01 10:22 UTC by h0peRL

2024-02-18 18:19 UTC, mnaray requested changes
Overall your PR seems fine to me, however there are some changes I require you to make before merging it into main. Please make sure to enforce these points carefully before requesting another review from me or @EllisArn. 

I corrected some of the typos I found on the fly, although I need you to fix the bigger faults listed below, as I am working on another issue.

Test cases to correct:
- [x] 1.1 => The test environment is Visual Studio 2022 plus its version number. .NET 8.0 is the runtime
- [ ] 4.1 => Please define an API endpoint to use (like in 3.1)
- [ ] 5.1 => Please define the script more specifically in the requirement column.
- [ ] 6.1 => Please define the script more specifically in the requirement column.
- [ ] 9.1 => Could that be a nonexistent route? Please Check the Controller's class diagram. There was no intention to create a help command.
- [ ] 10.1 => Please provide a concrete endpoint to run this test on.
- [ ] 13.1 => A glossary contains translations **and** explanations.

Further problems related to this PR:
- [ ] Missing definition of a test environment. Please include all the version/build numbers of the programs and runtimes listed in it. See old projects for examples.
- [ ] Requirement 11 is wrong. This would be an opportunity to fix it. We won't necessarily be using commands on our REST API. Instead, we'll offer endpoints through controller objects. To document those, we could add a .../endpoint/info route to (or similar) to every endpoint.
- [ ] Column names of the test case table are written in German. Please translate those to English.

_Additional note:_
Please make sure to pay attention to accidental removal of indentations by the markdown editor. I had to manually readjust the indentations of the blue boxes. This requires you to take a peek at your diff before committing and pushing your changes.

2024-02-21 07:55 UTC, h0peRL reviewed
I applied all the requested changes.

2024-02-22 06:37 UTC, mnaray requested changes
- [x] Remove the empty column from the requirements.
- [x] Fix the indentation issue with the blue box for the lesson calculations. (Please remember to check your diff before committing)
- [x] Please make sure that you use version numbers that are up-to-date.
- [x] Fix the Bulletpoint's indentation.
- [ ] 9.1's route would be .../booking/book

2024-02-22 06:37 UTC, mnaray commented on docs/project/documentation.md
> +| :----------- | ---------------------- | :---------------------- | ---------------------------------------------------------------------------------------------- | --- |
I think you might have added an accidental column here.

2024-02-22 06:37 UTC, mnaray commented on docs/project/documentation.md
> -    Here is the calculation of how many lessons the project should take to implement. Please note, that a single lesson equals 45 minutes
You removed the needed indentation again in this section.

2024-02-22 06:37 UTC, mnaray commented on docs/project/documentation.md
> +**The total amount of lessons should be 105** as every one of the 3 members works 5 lessons per week over the course of 7 weeks.
Everything up to this line should be included.

2024-02-22 09:36 UTC, mnaray approved these changes

2024-02-22 09:37 UTC, merged